### ISSUE TITLE
Add support for creating Route53 verification DNS

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-ses-wp-mail#1]
Would be cool - however it's presumed that the IAM keys that someone defines will only be able to access SES (if they configured it right) so having hte ability to pass a key/secret into this would be handy.

**Comment by rmccue** [comment]
The AWS console already provides this functionality, so there's no real benefit to us doing it. In fact, it's a worse experience, as you'll likely need to provide the key and secret manually. It's also not a particularly trivial feature to implement, as we'd need UI for entering key/secret etc etc.

In light of that, closing.
