### ISSUE TITLE
trigger_error has too many parameters

### ISSUE THREAD

**Issue by kevinlisota** [humanmade/aws-ses-wp-mail#23]
When Amazon SES returns an error, your code uses PHP's trigger_error. However, that function expects two parameters not four, as you are sending.

https://github.com/humanmade/aws-ses-wp-mail/blob/master/aws-ses-wp-mail.php#L29

This results in the following PHP warning: PHP Warning: trigger_error() expects at most 2 parameters, 4 given in /wp-content/plugins/aws-ses-wp-mail/aws-ses-wp-mail.php on line 29

**Comment by rmccue** [comment]
Thanks, good catch!
