### ISSUE TITLE
Gravity Forms HTML email notifications formatting issues and incorrect from email

### ISSUE THREAD

**Issue by kevinlisota** [humanmade/aws-ses-wp-mail#24]
We use Gravity Forms on our site and use their notifications to send out HTML email notifications upon form submission. We are seeing two different issues when using the AWS SES WP Mail plugin.

1) The "from" address is not being picked up correctly. In Gravity Forms notifications, it allows you to set the "From Name" and "From Email." When notification is sent from this plugin, the "From Name" is correct, but the "From Email" is not. Regardless of what the "From Email" is, it creates a pseudo email address of the form "wordpress@www.mydomain.com"

2) Gravity Forms also uses HTML formatting in its forms notifications. Rather than parsing the HTML formatting, email sent using this SES plugin is showing the raw HTML tags.

I've used other plugins like wpMandrill in combination with Gravity Forms with success, and seems like an important plugin for this mailer to work with. Any ideas? I know that SES supports HTML email, so guessing there is some issue with the format of the API call?

**Comment by rmccue** [comment]
See https://github.com/humanmade/aws-ses-wp-mail/issues/20#issuecomment-302631659 for details on why it's breaking. #31 will fix this. :)
