### ISSUE TITLE
Update AWS sdk as its out of date.

### ISSUE THREAD

**Issue by andrewmclagan** [humanmade/aws-ses-wp-mail#40]
`count(): Parameter must be an array or an object that implements Countable in /var/www/wp-content/plugins/aws-ses-wp-mail/lib/aws-sdk/GuzzleHttp/Handler/CurlFactory.php on line 67`

**Comment by andrewmclagan** [comment]
see https://github.com/guzzle/guzzle/issues/1973

**Comment by tareiking** [comment]
Yo @andrewmclagan - long time (Tripleshot Creative Brisbane days long). 

@joehoyle what's typically involved in updating the AWS SDK for this library? I can happily draft an update PR, but unsure what / if we need any feature testing during the process for this.

**Comment by joehoyle** [comment]
@tareiking you'd bump https://github.com/humanmade/aws-ses-wp-mail/blob/master/composer.json and then copy vendor to lib, that's the most of it. As it happens, we don't use the bundled version ala https://github.com/humanmade/aws-ses-wp-mail/blob/master/inc/class-ses.php#L200 so I think that's why we haven't seen this.

**Comment by andrewmclagan** [comment]
@tareiking hey man! How are you? Here are you these days!?

**Comment by hisham** [comment]
Any update on this? Still occurring.

**Comment by rmccue** [comment]
@joehoyle should we copy over the S3 Uploads build script?

**Comment by joehoyle** [comment]
@rmccue yeah sounds like a good idea.

**Comment by roborourke** [comment]
The bundled copy of the SDK was removed in #41 so closing this out. We should loosen the composer.json version constraint though to `^3.x`

**Comment by roborourke** [comment]
Ok that PR was ages before this ticket, reopening!
