### ISSUE TITLE
Support Reply-To header

### ISSUE THREAD

**Issue by jchristopher** [humanmade/aws-ses-wp-mail#7]
It looks like the `Reply-To` header is getting lost along the way (set via Gravity Forms in my case)

**Comment by joehoyle** [comment]
This should now be fixed I think, would you mind pulling the latest master branch and giving this another go.

**Comment by jchristopher** [comment]
Just checked it out and unfortunately it doesn't appear to be working. Will try to take some time to dig deeper in the coming weeks. Thank you very much for working on this!
